### ISSUE TITLE
First blog post - comments and tone of writing

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#16]
So I came up with a first quick draft for the blog post. Kevin made a comment that I think is worth delving into a bit more. 

Writing as a group is not easy, and this first blog post can kind of set the tone for how other posts are written. I obviously came up with something much lighter with some attempts at being funny, which means that I set a tone for the onset. I happen to think light and funny is the best, because then you can easily add feelings to how you write, and let’s be frank, that’s how you get people’s interest, not when you write scientifically. But that’s my opinion and it may not reflect everyone’s, and it doesn't have to stay that way. 

I think a conversation on the tone is necessary and it would be nice if everyone could chime in on the topic. I think we are all comfortable enough to speak our minds without restraint, so fire away. If you guys think we need to throw this in the garbage, by all means say so and I'll be perfectly comfortable with the idea! 

And any case, edit the post as much as you wish! [Here it is!](https://github.com/inSileco/inSileco.github.io/blob/master/_posts/_Intro.Rmd)

**Comment by david-beauchesne** [comment]
Comment from @remi-daigle, add what inSileco means in the post

**Comment by remi-daigle** [comment]
Yep, light and funny I think is the way to go here! We all read enough dry stuff day to day.

Just a note @david-beauchesne and I already chatted about is that our posts are probably mostly going to be rather technical, which means we can easily insult many beginners if we are not careful about the expressions that we use. So I'd recommend not saying things like "JUST do x", or "This is EASILY done...". Remember that what is easy to us may not be easy to our readers!

Also, a general note that we should include a statement, formal or not, about the motivation and the learning objectives for each post

**Comment by david-beauchesne** [comment]
This will be integrated in the new version of the website, with a few modifications. Once the new website is launched, if you guys have further comments, we can change is again!
