### ISSUE TITLE
Hugo integration

### ISSUE THREAD

**Issue by SteveViss** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#19]
# Dev on the branch dev_visual: 

## Responsive website

- [ ] Avoid flatten logo/banner to improve responsive design.
- [x] Fix responsiveness of the blog pages (issue with `col-sm-12`).

## Home page:

- [ ] Add the 5 most common tags -> Link to one page by tag with all posts related
- [X] Add the 5 latest blog post on the home page
- [X] Add twitter timeline

## Blog posts integration with Hugo:

- [X] Match author ids with their profiles in order to add hyperlink to Github/researchGate/ORCID/twitter
- [X] Add twitter button
- [x] Add status (Draft are automatically unpublished, In revision and Final version)
- [ ] Setting up image variable in the header to allow user to setup their own banner.

## Softwares page:

- [X] One YAML by softwares with a quick description
- [X] Link to Travis/Codecov etc.. 

## About page:

- [X] For each author, display their github avatar profile (e.g. https://avatars.githubusercontent.com/kevCaz)
- [X] One YAML by author

## Author helpers:

- [x] Create an archetype: default YAML when you call `blogdown::new_post()`
- [ ] Create documentation on external ressources related/needed to the post
- [X] Develop an automated installation procedure for any packages needed by the posts (making sure new author/Travis will have any troubles rebuilding the site locally).

**Comment by SteveViss** [comment]
## Workflow improvements:
1. Open a _edit_ branch and set as the default branch
2. When any pushes are made on the _edit_ branch by authors, Travis will be in charged to build up the new website - Travis don't messup ;) and then to push the new website to the master _branch_. Only the public folder content will be on the master branch (*.html files).

**Comment by david-beauchesne** [comment]
@SteveViss, me and @KevCaz were wondering when you were planning to officially change the website? There is absolutely no rush, we are just wondering, and if you need any help with anything? If so let us know, we'll give a hand happily!

**Comment by SteveViss** [comment]
I might need some help in reintegrating old posts, but I think I can (this afternoon) published the new website even if minor features are not ready.

**Comment by KevCaz** [comment]
Sounds perfect Steeve! I will have some time this week to implement the missing features! 
The sooner you release the website, the better!

**Comment by SteveViss** [comment]
Added responsive TODO section

**Comment by KevCaz** [comment]
This is a great todo list @SteveViss ! 

I wa discussing with Miste and he brings my attention to the responsiveness issues for the post pages. Now I know that you are aware of that!! :)

**Comment by KevCaz** [comment]
I can help with the archetype :)

**Comment by SteveViss** [comment]
@KevCaz , sure fill free to give a try. Let me know if you have some concerns.

**Comment by KevCaz** [comment]
We do have archetypes now. @SteveViss is there anything that we need to do? Otherwise, I'll close this issue, and we could open specific issues if needed.

**Comment by SteveViss** [comment]
Yes, let's close it.
