### ISSUE TITLE
Bayesian stats blog series 

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#20]
Freshly coming off a week of doing bayesian statistics for a lot of us, myself, @KevCaz and @SteveViss have discussed the possibility of coming up with a series of blog posts on the use of bayesian stats in ecology. With Kevin, here are a few thoughts we've had for the posts. If you are interested in helping out or have ideas of your own, please feel free to comment!

**Series title**: Bayes in Ecology, Ecology of Bayes, etc?

1. Bayesian statistics phylosophy (general post on bayes and the structure of the series of blog posts) (w/ formula)
2. Conjugate (material ready, @KevCaz)
3. Prior & posteriors (material ready, @KevCaz)
4. Data choice/impact
5. Bayes vs frequentist approach (material ready, @KevCaz)
6. Revisit classic foundational paper in ecology that uses a frequentist approach
7. Metropolis-Hastings (rcpp, @KevCaz)
8. Hierarchical models (Gibbs w/ metropolis hastings)
9. How to interpret results (Metrics to interpret results)
10. Existing Bayesian tools
11. Bayesian model averaging

HEADER: short description of blog series that is repeated in every post of the series, to include in the yaml portion of the rmd.

**Comment by KevCaz** [comment]
Regarding this, I an thinking about writing a series more general math-oriented.

**Comment by KevCaz** [comment]
1- context + phylosophy + resources (blog / distributions/ ...)
2- likelyhood 
3- lm 
4- glm

**Comment by KevCaz** [comment]
I created this repo. Instead of post I think for series books make more sense! 
https://insileco.github.io/StatsMaths/

**Comment by KevCaz** [comment]
Won't do it.... at least not in a foreseeable future.
