### ISSUE TITLE
Author information - yaml files per contributors

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#23]
Ok, so we need to update the authors/contributors for the site. It is quite simple, you need to fill in a separate yaml file per author.

Go to `./data/authors/`, copy a file there and fill out the yaml header with your information. Push and commit your newly created yaml file with your name as the file name. Keep the name super(!!) simple, it's what we use in the posts to identify authors. The website will be automatically updated once you add in your information.

This task is for the people who are not already on the website:

- @eldre 
- @Azenor 
- @mathbess

**Comment by david-beauchesne** [comment]
Quick reminder @eldre, @Azenor and @mathbess, this issue is for you guys if you want to get your profile up on the website! 👍

**Comment by KevCaz** [comment]
I think we should close this and we should include this in a *how to contribute section*
