### ISSUE TITLE
Let's make TraviSteve's life easier. 

### ISSUE THREAD

**Issue by KevCaz** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#24]
We should find a way to lighten the build of our website and come up with a strategy to archive former posts. 

So far, we we push a new post, Travis builds the website from scratch which means it installs all R packages needed and their dependencies (*i.e.* additional R packages and other numerical tools such as pandoc). This is pretty cool as this workflow makes our blog a reproducible one. That being said, it also means that 
the version of the numerical tools will be permanently updated (and used as such for newer posts) and thereby we may encounter some issues with posts using a different version of the same package. 

In order to address this version issue and lighten the build:

1- once the post is reviewed, we should remove the `.Rmd` files from the post folder and only keep the `.html` version only (a `.md` version may be a better option);

2- then we should find a way to archive all `.Rmd` files associated with these posts (*i.e.* store them in a specific folder and add a link in the `md` or `html` version).

**Comment by KevCaz** [comment]
@SteveViss, 

Since you are the one that has played with the cache, do you think the build is Ok now or do you see any way to improve the build?

**Comment by SteveViss** [comment]
I see no way to improve the build for the moment. From what I know, if some packages are time consuming to install, we can always set up the install by writing them in the DESCRIPTION file instead of the *.Rmd files. By doing it, we ensure that package will be cached.
