### ISSUE TITLE
Post series on Mathematical Modeling

### ISSUE THREAD

**Issue by Azenor** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#26]
Hi gang,
@willvieira and I thought of doing a series of post on mathematical modelling inspired from a workshop we are doing at the uni on the book "A Biologist's guide to Mathematical Modeling in Ecology and Evolution" from Otto and Day. We wrote a short description of the posts here. Let us know what you think about the idea, the structure and if you'd like to participate! :) 

# Mathematical Modeling in Ecology with R

## Post 1
Why mathematical modeling?

Advantages and disadvantages.

* Chapter 1: introduction

* Chapter 2: how to construct a model?

Example of a simple model in R. (Two species mutualism interaction model?)

## Primer post ?!

Linearization

## Post 2

Equilibria and stability analysis of the model introduced previously (Chapter 5).

Package `DeSolve` and `rootSolve`

* Find the equilibria: `ode()`, `runsteady()`, `multiroot()` and other functions
* Determine its stability: `jacobian.full()`...
* Difference between linear and non linear models, techniques for non linear models.

## Post 3

Graphical representation of stability analysis

Phase plan: Illustration of eigenvectors (associated to eigenvalues). (Van der Pol oscillator?)

## Post 4

General solutions and linear algebra

## Post 5

Probabilistic models: add stochasticity to our toy model and analyze it

## Post 6

Analyzing continuous stochastic models: Diffusion in time and space

**Comment by KevCaz** [comment]
What a great idea!! 👍 👍  and I want to be involved, let me in, please, please!!! 

It's a vast topic though and from what I am reading you won't actually cover everything (I mean of course you won't and you don't have to but we may refine the title according to the topics you are covering, *e.g.*: *a taste of differential equations in R*). 


Regarding the structure I have a couple of suggestions. 

First, I think that the question:

>Why mathematical modeling? 

you've righteously asked should be the topic of **first post** of the series. You may first ask *why model?* (google have proven me that we won't be the first asking this question! http://jasss.soc.surrey.ac.uk/11/4/12.html) than briefly mention what king of model exist and then detail the scope of the collection of posts and especially if theses posts will have a math focus or an *in silico* focus or both (everything would suit me well).

In **post 2** you could give a simple example of ODE (and give some context about ODE) and I think it would be a wonderful idea to create a function to visualize the ODE (I've already done that). I really think it would be worth spending some time discussing about the mathematical object we are dealing with before 
*solving* it. 

**Post 3** may discuss about the numerical methods available to solve ODE and you may provide home-made code lines that implement them (*e.g.* Euler, Runge-Kutta). 

In **post 4** you could detail how to solve ODE with `DeSolve` and `rootSolve` (and detail what they are actually using). I now use `odeintr` and I can show how to use it. We may carry some benchmarking out. 

In **post 5**, you could spend some time about what to do with the results or even deal with sensitivity analysis.  

I think that would enough for now, we can plan solving other kind of equations latter. Dealing with diffusion can easily be 3 other posts and dealing with master equations 3 others!! Let's start with a reasonable number of posts. Again the above suggestions are **by no means** guide lines and only reflect my sole opinion. Anyway you'll do, this it will be a nice collection of posts to show how to solve differential equations in R or whatever. 

A side note we can also give some mathematica / sage command line to solve equations.

**Comment by Azenor** [comment]
Hey!
We briefly updated the posts series ideas after Kevin comments. @willvieira, @KevCaz and I will start writing them. If you're interested in joining, you're more than welcome, comment here :)

# Mathematical Modelling in Ecology: a taste of differential equations in R

## Post 1: Introduction
* Why models? Interest.
* Types of model, examples
* Structure and ideas of the post series (*In silico* focus)
* Briefly describe the 7 steps to make a model (detailed in later posts)

## Post 2

* Introduction on differential equation (context)
* Describe toy model: simple example of ODE + its flow diagram
* Function to visualize the ODE (Kevin example)

## Post 3

* Equilibria and stability analysis (context, eigenvalues and eigenvectors)
* Numerical methods to solve ODE
* Home-made solutions (Euler, Runge-Kutta)

## Post 4

* Package `DeSolve` and `rootSolve`
* Find the equilibria: `odeintr()`, `ode()`, `runsteady()`, `multiroot()` à voir...
* Determine its stability: `jacobian.full()`...
* Graphical representation of equilibria (Phase plan)


## Post 5

* What to do with the results
* Graphical representation
* Sensitivity analysis

**Comment by KevCaz** [comment]
Any idea about what the timeframe could be?

**Comment by Azenor** [comment]
Aha yeah I was completely busy with my predoc but now I can start! I can work on the first post this week/next week.

**Comment by willvieira** [comment]
https://github.com/inSileco/inSileco.github.io/commit/57f6cd8f302bbfc1e392afbe32dc4cfd1ffcc734
