### ISSUE TITLE
Single or series of posts of spatial data viz

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#27]
Write a post on visualizing spatial data in R, tips and pitfalls, simple shiny app for interactive visualization. @SteveViss @KevCaz @ahasverus @Thomzgi

**Comment by KevCaz** [comment]
I'll work on the first post on next week (quite busy all this week).

**Comment by david-beauchesne** [comment]
What'll the post be about?

**Comment by KevCaz** [comment]
empty your plot!

**Comment by david-beauchesne** [comment]
This issue will be included in the issue on R in Space
