### ISSUE TITLE
Adjust function names in posts using `showtext` package

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#28]
In the latest version of the `showtext` package, the functions have transitioned from using `_` to `.` in functions, *e.g.* `add.font.google()`. We should adjust the posts to reflect this change.

**Comment by KevCaz** [comment]
@david-beauchesne I think it is the other way around... 

```
R>> font.add(family = 'Academicons', regular = 'academicons.ttf')
'font.add()' is now renamed to 'font_add()'
The old version still works, but consider using the new function in future code
```
