### ISSUE TITLE
Add shiny app?

### ISSUE THREAD

**Issue by KevCaz** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#44]
Do you want to add your shiny apps on the software page? If so I'll do it :)

**Comment by david-beauchesne** [comment]
Very late in answering this, but I think that we should link them yes!

**Comment by KevCaz** [comment]
Ok let's add a page in the new resources section

**Comment by david-beauchesne** [comment]
https://david-beauchesne.shinyapps.io/edriversapp/
