### ISSUE TITLE
R in Space, a spatial and educational blog post series

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#48]
I suggest building a series of blog posts that can be used as lessons that show multiple facets of making maps in R and working with spatial data. The goal would be to build a series of posts that could be used in an educational setting to show how to work with spatial data, perform spatial analyses, visualize spatial data and some cartography stuff. 

Part of this series would be used shortly for a student retreat in April where students are interested in learning about cartography. 

Here are a few points that are interesting for us:

- `sf` is making great strides and will replace `sp` whether people like it or not (I happen to like it)! It could be an opportunity for people who are not yet familiar with `sf` to learn. 
- increased visibility for inSileco
- blog post series on something that represents well the members of this group
- educational material and experience 
- write a post on visualizing spatial data in R, tips and pitfalls, simple shiny app for interactive visualization (from previously opened issue)

**Comment by KevCaz** [comment]
I guess we can close this. Let's re-open an new issue when we want to update the current series of posts: 
https://insileco.github.io/2018/04/14/r-in-space---a-series/
