### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by KevCaz** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#5]
We should definitely find an efficient way to handle references throughout the blog. 

We could probably start with 1 `.bib` file per blog post to let the first author handle the references he needs (for a specific blog post). This could be easily done using the yaml-header. We could store the `.bib` files in the post-dedicated subfolder in `asset`, i.e. the subfolder where we should include all material the blog post requires.

Any thoughts? Any better strategy?

**Comment by david-beauchesne** [comment]
I feel like we need something more general if we start building series of lit reviews. Surely references will become duplicated as posts multiply. Does it make sense to duplicate the data as well?

**Comment by KevCaz** [comment]
Right! We can have bigger thematic `.bib` files. Actually whatever we are up to, it only requires to add the correct option in the head-yaml.

**Comment by KevCaz** [comment]
We have discussed this with Dave and we have got some insights into that question. It is possible to get a list of DOIs and then retrieve all ref from that list. There are R packages available that would make our life easier (and it may exist some efficient Javascript library and/or python libraries). I think we can implement a couple of functions to help us managing our bibliography for the blog and add them in letiRmisc.

**Comment by david-beauchesne** [comment]
I created a package, [*inSilecoRef*](https://github.com/inSileco/inSilecoRef), that updates a `.bib` file using a list of DOIs. See CONTRIBUTING file for a description of how to include in-text citations and a bibliography to posts. This is a first attempt at group reference management taking advantage of DOIs. There is still a need for development, but for now we can easily include a citations and a bibliography using common markdown citation procedures.

**Comment by KevCaz** [comment]
I will move the bib folder to static and change the R script accordingly as it currently upsets Hugo!

**Comment by KevCaz** [comment]
in 8e4cab677008688e14e535619b70e0ef7d246d62 I introduces new files. The R script now generates `static/bib/DOIRef.bib` then I use [bibtool](https://ctan.org/pkg/bibtool) to merge `static/bib/DOIRef.bib` with `static/bib/noDOIRef.bib` (where ref without DOI are stored) into `static/bib/inSilecoRef.bib`
