### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by remi-daigle** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#62]
I can't pull the site from github using a Win 10 machine. 

The problem seems to be the [`ionicons.tff?raw=true`](https://github.com/inSileco/inSileco.github.io/tree/dev/content/post/iconsInR/assets)
The error message is:

```
error: unable to create file content/post/iconsInR/assets/ionicons.ttf?raw=true: Invalid argument
Checking out files: 100% (421/421)   
Checking out files: 100% (421/421), done.
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

**Comment by KevCaz** [comment]
Thanks @remi-daigle for reporting this,

So we should definitely add AppVeyor + I'll check the file that causes the issue.

**Comment by KevCaz** [comment]
cac51eebafd81bdac03e7ca7a52d89af98f26036 removes the problematic icon file and adds appveyor.yml
Let's wait and see.

**Comment by KevCaz** [comment]
And the bug was reproduced https://ci.appveyor.com/project/KevCaz/insileco-github-io/build/1.0.1

**Comment by KevCaz** [comment]
We'll need some time to set AppVeyor properly in the meanwhile @remi-daigle would you mind checking if you are able to clone the repo?

**Comment by remi-daigle** [comment]
seems to work now!!
Are we closing this issue?

**Comment by KevCaz** [comment]
I'd feel better if we would close this after making Appveyor work properly!

**Comment by KevCaz** [comment]
Not there yet, I'll read the Appveyor doc .... maybe latter this week.

**Comment by KevCaz** [comment]
I finally got it. I had to remove one post (on Appveyor, not on Travis). Not really satisfied by this so I may find a way to make this post (iconsInR) work on windows before closing this.

**Comment by KevCaz** [comment]
Done! 

I explain what I did here https://kevcaz.github.io/notes/r/blogdownappveyor/.

**Comment by remi-daigle** [comment]
confirmed! Thanks @KevCaz I can now pull the site AND host the site locally!

**Comment by KevCaz** [comment]
Glad it worked @remi-daigle  ! We should have set AppVeyor before, I wrongly assumed we all were on MacOS/Linux, my bad!
