### ISSUE TITLE
Come up with new name for blog

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#7]
Per @KevCaz's idea, we should come up with a new name for the blog and start a brainstorm on the subject. To facilitate this, I propose writing our first, collective, blog post that describes briefly who we are, the goals/objectives of the blog and the letir group, and the type of content that we will be building.

**Comment by SteveViss** [comment]
Ailuropoda melanoleuca ;)

**Comment by david-beauchesne** [comment]
Haha @KevCaz would like that idea !

**Comment by KevCaz** [comment]
How shall we proceed for collective posts?

**Comment by SteveViss** [comment]
geecko

**Comment by SteveViss** [comment]
What about blob? http://www.futura-sciences.com/planete/actualites/botanique-blob-physarum-cellule-geante-cerveau-apprend-62597/ hahaha or bloom?

**Comment by remi-daigle** [comment]
covfefe, or maybe something more straightforward...

**Comment by KevCaz** [comment]
After some brain-storming on slack, I think INSILECO / inSILECO could work!

**Comment by david-beauchesne** [comment]
Name chosen is now inSileco. First blog post is underway, see [rmd file](https://github.com/inSileco/inSileco.github.io/blob/master/_posts/_Intro.Rmd) and review!

**Comment by KevCaz** [comment]
Once written and released, we will close this :)

**Comment by remi-daigle** [comment]
wait, what does it mean?

**Comment by KevCaz** [comment]
inSileco?

**Comment by david-beauchesne** [comment]
playing with this: https://en.wikipedia.org/wiki/In_silico 
adding ecology into it

**Comment by remi-daigle** [comment]
AHHHH, I like it! (although, maybe that needs to be explained here https://github.com/inSileco/inSileco.github.io/blob/master/_posts/_Intro.Rmd )

**Comment by KevCaz** [comment]
Guys, guys, we should make the Acronym a pseudo-recursive one. 

inSileco: inSilico Ideas and Lucubrations for ECOlogy

How does it sound?
