### ISSUE TITLE
Add twitter account and twitter feed

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#8]
We should create a twitter account and add a twitter feed with all tweets from ourselves and the letir account on the home page. 

I haven't created an account because @letir is already taken. Since we want to come up with a new name for the blog, I figured that we could merge them together for a twitter account name (see Issue #7), *e.g.* @letir_REcol (révolution écologique!).

**Comment by david-beauchesne** [comment]
https://github.com/rob-murray/jekyll-twitter-plugin/blob/master/README.md

**Comment by KevCaz** [comment]
Twitter feed would be nice to add a News section to our the website 

See also => https://dev.twitter.com/web/overview

**Comment by KevCaz** [comment]
I've added tweet buttons to share our blog posts in 856da3a13130cb12ccbf167193f0bfbff3919816! As soon as we get Twitter account I'll be able to link the button to our account.

**Comment by david-beauchesne** [comment]
The twitter account is now set, meet @inSileco

**Comment by KevCaz** [comment]
and Steve has added the time line which is still empty.... but not for long!! 

Thanks @SteveViss  and @david-beauchesne. I am closing this issue.
