### ISSUE TITLE
Code tips blog series - Find catchy name!

### ISSUE THREAD

**Issue by david-beauchesne** [inSilecoBlogLegacy/inSilecoBlogLegacy.github.io#9]
I think the code tips blog series is a wonderful idea. Simple and fast to implement, with a big outreach potential. With that in mind, I would suggest finding a specific name for that blog series, one that is catchy and has an *obscene* component to it, *e.g.* *Shit academics say*. 

Any suggestions?

**Comment by SteveViss** [comment]
Fish and tips? ;)

**Comment by KevCaz** [comment]
cody shit? ou alors un truc latin Lorem codum?

**Comment by KevCaz** [comment]
After Halloween time, I feel like *trick or tweak* could do the job??

**Comment by KevCaz** [comment]
Or *trick or tips*

**Comment by david-beauchesne** [comment]
my vote is for Fish or Tips!

**Comment by KevCaz** [comment]
So we change the current "and" for a "or".

**Comment by KevCaz** [comment]
@david-beauchesne : 

 > my vote is for Fish or Tips!

I think you meant **trick or tips** right?

**Comment by david-beauchesne** [comment]
indeed, that is what I meant! ;)

**Comment by KevCaz** [comment]
**trick or tips**, we all agree?

**Comment by david-beauchesne** [comment]
Let's give people until the end of the day to vote
